version: "2"
services:
  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - ${PORT}:8888
    networks:
      - tm351
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - tm351
    restart: unless-stopped

networks:
  tm351:
