version: "3.5"

services:
  tm351:
    image: jupyter/minimal-notebook
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    networks:
      - tm351
    ports:
      - ${PORT}:8888

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - 5432:5432
    networks:
      - tm351

networks:
  tm351:
